"""The card index: names, kinds, and copy limits for the codes the app deals in.

Two tiers, and the difference between them is the whole point (CONTEXT.md). The
**supported pool** is the 864 codes the frozen Pilot can represent. The *known* tier
is every other card in the executor's own `cards.cdb` -- the C++ core recognises it,
the Pilot cannot see it. Collapsing the two is how a user ends up told that a card
they own does not exist.

There is a third, smaller tier: alt-art printings. The same card ships under several
codes, `.ydk` exports carry whichever one the owner opened, and 60 of those codes name
a card that *is* in the pool. `resolve()` folds them onto the printing the Pilot knows,
so a supported card is not rejected for being the pretty version.

Membership still comes from `pool.txt` via `pool.supported_pool()`; this module only
adds what a human needs to read a decision about a card.

Generated by `tools/gen_card_index.py`, from sources pinned to the same commits the
ygoenv build fetches.
"""

from __future__ import annotations

import json
import os
import unicodedata
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from .models import Card, CardSection
from .pool import supported_pool

_REPO_INDEX = Path(__file__).resolve().parents[3] / "data" / "pilot-864" / "cards.json"

DEFAULT_COPY_LIMIT = 3


def index_file() -> Path:
    """Where to read the card index from. `AI_DRAW_CARDS` overrides the in-repo copy."""
    override = os.environ.get("AI_DRAW_CARDS")
    return Path(override) if override else _REPO_INDEX


def normalise(name: str) -> str:
    """Fold a card name to what a user is likely to have typed.

    Accents, quote styles and spacing all differ between the printed card, a
    decklist site's export, and a paste box. None of those differences should
    decide whether the app admits a card exists.
    """
    folded = unicodedata.normalize("NFKD", name)
    folded = "".join(ch for ch in folded if not unicodedata.combining(ch))
    folded = folded.replace("’", "'").replace("‘", "'")
    folded = folded.replace("“", '"').replace("”", '"')
    folded = folded.replace("—", "-").replace("–", "-")
    folded = folded.replace("－", "-")
    return " ".join(folded.lower().split())


@dataclass(frozen=True)
class Match:
    """One search hit. `in_pool` is never inferred by the caller."""

    card: Card
    rank: int


class CardIndex:
    """Lookup and search over the pool, with the rest of the card list behind it."""

    def __init__(self, payload: dict) -> None:
        self.banlist: str = payload["meta"]["banlist"]
        self._pool: dict[int, Card] = {}
        for code, entry in payload["pool"].items():
            self._pool[int(code)] = Card(
                code=int(code),
                name=entry["name"],
                kind=entry["kind"],
                subtypes=entry["subtypes"],
                section=CardSection(entry["section"]),
                race=entry["race"],
                attribute=entry["attribute"],
                level=entry["level"],
                atk=entry["atk"],
                defense=entry["def"],
                limit=entry["limit"],
                in_pool=True,
                desc=entry.get("desc") or None,
            )
        self._known: dict[int, str] = {
            int(code): name for code, name in payload["known"].items()
        }
        self._alias: dict[int, int] = {
            int(code): int(target) for code, target in payload.get("alias", {}).items()
        }

        expected = supported_pool()
        if tuple(self._pool) != expected:
            raise RuntimeError(
                "card index disagrees with the supported pool: "
                f"{len(self._pool)} indexed vs {len(expected)} in pool.txt. "
                "Rerun tools/gen_card_index.py."
            )

        self._by_name: dict[str, list[int]] = {}
        for code, card in self._pool.items():
            self._by_name.setdefault(normalise(card.name), []).append(code)
        for code, name in self._known.items():
            self._by_name.setdefault(normalise(name), []).append(code)

        self._main_deck: tuple[int, ...] = tuple(
            code
            for code, card in self._pool.items()
            if card.section is CardSection.MAIN and card.limit > 0
        )

    def __len__(self) -> int:
        return len(self._pool)

    @property
    def pool(self) -> dict[int, Card]:
        return self._pool

    def main_deck_codes(self) -> tuple[int, ...]:
        """Pool cards that may legally sit in a main deck, forbidden ones removed.

        Only 411 of the 864 are main-deck cards at all -- 408 once the banlist has
        taken three of them -- because the pool is the Pilot's *vocabulary*: it
        covers the Tokens and Extra Deck monsters the Pilot has to recognise on the
        field, not just the cards a deck can be built from. Handing the executor a
        deck containing a Token is not a rejected deck, it is a dead process.
        """
        return self._main_deck

    def resolve(self, code: int) -> int:
        """Fold an alt-art code onto the printing the index carries.

        Pool membership wins: 59 pool codes are themselves aliases, and the Pilot
        has an embedding row for that exact code, so they resolve to themselves.
        """
        if code in self._pool:
            return code
        return self._alias.get(code, code)

    def get(self, code: int) -> Card | None:
        """The card for a code, whether or not the Pilot can represent it."""
        code = self.resolve(code)
        card = self._pool.get(code)
        if card is not None:
            return card
        name = self._known.get(code)
        if name is None:
            return None
        return Card(
            code=code,
            name=name,
            kind="unknown",
            subtypes=[],
            section=CardSection.MAIN,
            limit=DEFAULT_COPY_LIMIT,
            in_pool=False,
        )

    def by_name(self, text: str) -> list[Card]:
        """Every card whose name matches exactly, once folded. Usually one."""
        codes = self._by_name.get(normalise(text), [])
        return [card for card in (self.get(code) for code in codes) if card is not None]

    def search(self, query: str, *, limit: int = 20, unsupported: bool = True) -> list[Card]:
        """Name search, pool first. Rank: exact, then prefix, then substring.

        Unsupported cards are returned by default and marked `in_pool: false`. A user
        searching for a card the Pilot cannot play deserves to be told that, not to
        be shown an empty box and left to conclude the search is broken (ADR-0005).
        """
        needle = normalise(query)
        if not needle:
            return []

        hits: list[tuple[tuple[int, int, str], Card]] = []
        for code, card in self._pool.items():
            rank = _rank(normalise(card.name), needle)
            if rank is not None:
                hits.append(((rank, 0, normalise(card.name)), self._pool[code]))
        if unsupported:
            for code, name in self._known.items():
                rank = _rank(normalise(name), needle)
                if rank is not None:
                    card = self.get(code)
                    if card is not None:
                        hits.append(((rank, 1, normalise(name)), card))

        hits.sort(key=lambda hit: hit[0])
        return [card for _, card in hits[:limit]]


def _rank(name: str, needle: str) -> int | None:
    if name == needle:
        return 0
    if name.startswith(needle):
        return 1
    if needle in name:
        return 2
    return None


@lru_cache(maxsize=1)
def card_index() -> CardIndex:
    path = index_file()
    return CardIndex(json.loads(path.read_text(encoding="utf-8")))
